// <auto-generated />
namespace TB181979_desafio01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MigracionInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracionInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202109170527347_MigracionInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
